name: Terraform Workflow

on:
  push:
    branches:
      - dev

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.6

      - name: Lint Terraform code
        run: |
          terraform fmt -check -recursive

      - name: Initialize Terraform
        run: terraform init

      - name: Plan Terraform
        run: terraform plan
