name: Terraform Workflow

on:
  push:
    branches:
      - dev

  pull_request:
    types: [closed]
    branches:
      - main
      - dev
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Format Terraform code
        working-directory: ./
        run: terraform fmt

  plan:
    needs: lint
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.0
    - name: Terraform init
      working-directory: ./
      run: terraform init
    - name: Terraform Plan
      working-directory: ./
      run: terraform plan

  apply:
    needs: lint
    if: github.ref == 'main' && github.event.pull_request.merged == true   
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
    - name: Terraform init
      working-directory: ./
      run: terraform init
    - name: Terraform Apply
      working-directory: ./
      run: terraform apply -auto-approve


  destroy:
    needs: lint
    if: github.ref == 'dev' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
    - name: Terraform init
      run: terraform init 
      working-directory: ./
    - name: Terraform Destroy
      working-directory: ./
      run: terraform destroy -auto-approve
